[package]
name = "r_core"
version = "0.1.0"
description = "Rust bindings for radare2's r_core"
license = "MIT"
edition = "2018"
links = "r_core"
build = "build.rs"

[build-dependencies]
pkg-config = "0.3.16"
bindgen = "0.53.1"
