[package]
name = "r2api"
license = "MIT"
description = "rust bindings for the radare2 native APIs"
version = "5.6.1"
edition = "2021"
links = "r_core"
build = "build.rs"

[build-dependencies]
pkg-config = "0.3.16"
bindgen = "0.53.1"
