[package]
name = "analrs"
version = "0.1.0"
authors = ["defragger <rlaemmert@gmail.com>"]

[lib]
name = "analrs"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.18"
# rustc-serialize = "*"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
